### ISSUE TITLE
Add Liquidity

### ISSUE THREAD

**Issue by Edoumou** [Debond-Protocol/Pair-Contract#4]
[Reference](https://app.zenhub.com/files/461368354/99f7c6c9-4b80-4c3b-aa3b-bf886373389a/download)

# Description

Users add Liquidity and get **Bonds**. Only liquidity for one token is needed, the other token (which could be **DBIT** or **DBGT**) is then minted. In order to achieve this task one needs to proceed as follows

## Type of change

- [x] Create a function that checks if the token is listed by the Bank Contract
- [x] Create a function that updates token reserves
- [x] Create a function that updates ratios
- [x] Create a function that updates the price
- [x] Create a function that Adds liquidity
- [x] Compute functions Log and power (to calculate DBIT-USD price)

# How Has This Been Tested?

tested on Remix. Js unitary tests coming

- [x] Remix tests: add liquidity, check ratios factors, check prices
- [ ] JS mocha chai tests

# Diagram: Add liquidity

![addLiquidity.png](https://images.zenhubusercontent.com/621e3d56c366c123da8fb235/08022fb6-4b9f-48d7-a9f2-9ae6fccf7f51)

# Price calculation, ratio calculation

When users add liquidity to issue bonds, the price and the ratio factor can change. Price calculation as well as ratio calculation can be found in the file bellow.

[PriceCalculation.pdf](https://app.zenhub.com/files/461368354/b561e115-c9c7-4c8d-b7c6-9159ed49544f/download)

**Comment by Edoumou** [comment]
The Math library in Math-operations repo doesn't allow to compute ln(x) with x < 1, and since the DBIT price in USD is equal to 10^(ln(s/10^5)) where s is the total supply, we need to solve this problem also for $x < 1$, unless s > 10^5.

**Comment by dr-chain** [comment]
@Edoumou , This has been done by @toufic0710

**Comment by Edoumou** [comment]
Yes, that's why I removed it from the list of contracts that were blocking the issue.

**Comment by Edoumou** [comment]
@dr-chain

@GrandGarcon and I will connect the bank contract with the pair contract. @toufic0710 could also join the call if he can.

**Comment by Edoumou** [comment]
Needs review from: 
@GrandGarcon
@toufic0710
$@drikssy
@dr-chain
@gqkc

**Comment by GrandGarcon** [comment]
hi sam, just question regarding the input variables needed (as [here](https://github.com/Debond-Protocol/Pair-Contract/blob/samuel/contracts/PairContract.sol#L67)) currently the liquidity pair that you are going to add , does it has to be stored in the mapping of reserve (or create another mapping)?


also in the amountOfDebondToMint() ([here](https://github.com/Debond-Protocol/Pair-Contract/blob/samuel/contracts/PairContract.sol#L143)) , here the supply can be added by ISigmoidTokens(DBIT_address).totalSupply() and maxSupply()  (we  can take demo ERC20 template but there will be real implementation afterwards).

**Comment by Edoumou** [comment]
Hi @GrandGarcon,

Yes we don't need to map liquidity as we agreed yesterday, bonds value should tell how much tokens have been added. I  remove the mapping.

**Comment by toufic0710** [comment]
great prototype @Edoumou , however I have some remarks.

[Here](https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L143), you don't need to take as argument _dbitIn, because the amount of DBIT we have to mint is determined according to the value of tokenA (_amountToken in your code) that the user is going to deposit. For 1$ worth of token (we consider 1$ = 1 usdc), you will have to mint DBIT according to the formula in the whitepaper. So if a user wants to add x tokenA, we have to find the equivalent amount in usdc (let's say x'), then multiply this amount by dbitUSDPrice as you did [here](https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L153). Also, concerning the DbitUSDPrice function, I think there is a mistake [here](https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L176) : it's not "dbitTotalSupply * 1e13" but "dbitTotalSupply / 1e13". Also, we have to see with @yuliu-debond if it's possible to replace ln by log10, as it would save some gas. 
Now we know that we don't need _amountDBIT as an argument [here](https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L52), because this amount is determined by your amountOfDebondToMint function. But, we need a _minAmountDBIT argument : the users wants to be sure there is no price impact, and that the amount of dbit he expects to be minted is not going to change too fast. So, you will have to require that _minAmountDBIT<dbitAmount, as it is done in [uniswap](https://github.com/Uniswap/v2-periphery/blob/2efa12e0f2d808d9b49737927f0e416fafa5af68/contracts/UniswapV2Router01.sol#L35). 

Concerning the updateRatioFactor and updatePrice functions , I think the logic has to be implemented if the bank countract istead of here (as uniswap did). For the [addliquidity](https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L61) function argument's, it is not sure that the current format with _coinindex, etc.. will be kept so we have to keep in mind that this can be changed later. 
Also, the general logic has to be implemented : here there is a focus on dbit and dai because we don't yet have the structure to do otherwise, but when when we will have it we will have to remember to change it here, which means that your function will have to take in argument the two addresses (or something equivalent) of the token you are dealing with.
Finally, [here](https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L74), you are using bank.DBITcontract. We have to be clear about the structure : I understood that bank contract should store the data, but that bank contract is also the router calling the core contract, so these two contracts have to be merged. But we have to be sure that finally the data will not be stored in another contract only for data, so this has to be discussed...

**Comment by Edoumou** [comment]
@toufic0710 thank you for you comments. If I remember, @yuliu-debond said the amount of DBIT is an input, we need to tell how amountt DBIT we need and from that amount calculate the amount of DB2to mint, that's exactly what is done.

**Comment by drikssy** [comment]
one question pairContract is ERC3475?? (here)[https://github.com/Debond-Protocol/Pair-Contract/blob/6ea29b6b2b1ce9f6d16bd03177c9e44ca23d6f2a/contracts/PairContract.sol#L23]

**Comment by Edoumou** [comment]
As for the formula with 10^13, the calculation was made by @gqkc and we tested it he and I, these formula with 10^13 just works fine and thia value takes into account the fact that numbers must be input into Ether unit10^18, and since with have log(s / 10^5),we get exactly the factor 10^13 as derived by @gqkc

**Comment by Edoumou** [comment]
As for the logic, the function is not just about DAI and DBIT, it can be used with any pair that has been allowed by the Gov contract. The first input coinIndex means 

0 - DBIT
1 - DBGT

Can add more settlement tokens If needed.

**Comment by drikssy** [comment]
hello @Edoumou PairContract shouldn't inherit from ERC3475, I think u missed it, import the interface and instanciate it with a deployed ERC3475 (locally)

**Comment by Edoumou** [comment]
Hello @drikssy, yes it shouldn't, this was just for the purpose of testing. It seems like some of functions should move to pair contract and Dhruv already did it, I means he import the interface and not the contract.

**Comment by GrandGarcon** [comment]
ok so indeed i am importing the  PairContract now  , during  last week discussion there was confusion that whether pair Contract will be an seperate interface , with the debondRouter , in order to interact with the APM (pair functions and liquidity operations) , or its function  will be merged with the bank contracts ? so i will be for now keeping the seperation of the functions and easier to call via the interface
